package restaurantproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadeeeeeeeeeeen
 */
public class ManageMeals extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManageMeals
     */
    Connection conn;
        PreparedStatement pst;
        ResultSet rs;
	
    public ManageMeals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UpdateDelete = new javax.swing.JButton();
        ListItem = new javax.swing.JButton();
        AddItem = new javax.swing.JButton();
        MealDesktop = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        UpdateDelete.setBackground(new java.awt.Color(255, 255, 255));
        UpdateDelete.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        UpdateDelete.setText("Update/Delete");
        UpdateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleteActionPerformed(evt);
            }
        });

        ListItem.setBackground(new java.awt.Color(255, 255, 255));
        ListItem.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        ListItem.setText("List Items");
        ListItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListItemActionPerformed(evt);
            }
        });

        AddItem.setBackground(new java.awt.Color(255, 255, 255));
        AddItem.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        AddItem.setText("Add Item");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ListItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(UpdateDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout MealDesktopLayout = new javax.swing.GroupLayout(MealDesktop);
        MealDesktop.setLayout(MealDesktopLayout);
        MealDesktopLayout.setHorizontalGroup(
            MealDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        MealDesktopLayout.setVerticalGroup(
            MealDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MealDesktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MealDesktop)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListItemActionPerformed
       ListItem item =new ListItem();
       MealDesktop.add(item);
       item.setVisible(true);
      
    
       /* try {
               conn = Connect.connect();
           } catch (ClassNotFoundException ex) {
               System.out.println(ex);
           }
        String sql = "Select * from Items";
        try {
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
		while(rs.next()){
                Menu menu;
                menu = new Menu(rs.getInt("ID"),rs.getString("itemName"),rs.getString("itemCategory"),rs.getInt("itemPrice"));
                menuList.add(menu);
                        
                }
                        JOptionPane.showMessageDialog(null,"Listed Successfully");
                        
		}catch(SQLException se){
                    System.out.println(se);
                   
		}*/
     
     

    }//GEN-LAST:event_ListItemActionPerformed

    private void UpdateDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleteActionPerformed
      UpdateDelete item =new UpdateDelete();
      MealDesktop.add(item);
      item.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_UpdateDeleteActionPerformed

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
      AddItem item =new AddItem();
      MealDesktop.add(item);
      item.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AddItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItem;
    private javax.swing.JButton ListItem;
    private javax.swing.JDesktopPane MealDesktop;
    private javax.swing.JButton UpdateDelete;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
