package restaurantproject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




import java.awt.List;

/**
 *
 * @author nadeeeeeeeeeeen
 */
public class ManageEmp extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManageEmp
     */
  
    public ManageEmp() {
        initComponents();
     
       
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        List = new javax.swing.JButton();
        UpdateDeleteB = new javax.swing.JButton();
        AddDesktop = new javax.swing.JDesktopPane();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        Add.setBackground(new java.awt.Color(255, 255, 255));
        Add.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        List.setBackground(new java.awt.Color(255, 255, 255));
        List.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        List.setText("List");
        List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListActionPerformed(evt);
            }
        });

        UpdateDeleteB.setBackground(new java.awt.Color(255, 255, 255));
        UpdateDeleteB.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        UpdateDeleteB.setText("Update/Delete");
        UpdateDeleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleteBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateDeleteB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(List, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(UpdateDeleteB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout AddDesktopLayout = new javax.swing.GroupLayout(AddDesktop);
        AddDesktop.setLayout(AddDesktopLayout);
        AddDesktopLayout.setHorizontalGroup(
            AddDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        AddDesktopLayout.setVerticalGroup(
            AddDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        getContentPane().add(AddDesktop, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListActionPerformed
        LISTJInternalFrame emp=new LISTJInternalFrame();
       AddDesktop.add(emp);
       emp.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_ListActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
     ADDJInternalFrame emp=new ADDJInternalFrame();
     AddDesktop.add(emp);
     emp.setVisible(true);
     
       // TOleDO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void UpdateDeleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleteBActionPerformed
       UpdateDeleteEmp emp=new UpdateDeleteEmp();
       AddDesktop.add(emp);
      emp.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateDeleteBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JDesktopPane AddDesktop;
    private javax.swing.JButton List;
    private javax.swing.JButton UpdateDeleteB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
