/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantproject;



/**
 *
 * @author nada
 */
public class Meals extends javax.swing.JFrame {

    /**
     * Creates new form Meals
     */
    public Meals() {
        initComponents();
        this.setSize(965,740);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(WIDTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
       // jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
       
        jLabel1.setFont(new java.awt.Font("Constantia", 3, 48)); // NOI18N
        jLabel1.setText(" Menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 150, 50);

       // jButton2.setBackground(new java.awt.Color(153, 0, 102));
       // jButton2.setForeground(new java.awt.Color(102, 0, 102));
       // jButton2.setText("View Offers");
       /* jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });*/
      //  getContentPane().add(jButton2);
        //jButton2.setBounds(720, 10, 130, 50);

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel2.setText(" MainDishes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(41, 130, 220, 50);

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 26)); // NOI18N
        jLabel3.setText("         Dessert");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 130, 170, 50);

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 27)); // NOI18N
        jLabel4.setText("      Drinks");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(680, 130, 140, 40);

        jLabel7.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel7.setText("     Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 190, 100, 40);

        jLabel8.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel8.setText("   Price");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 190, 80, 40);

        jLabel5.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel5.setText(" Cordon bleu");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 250, 170, 40);

        jLabel6.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel6.setText(" 90");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 250, 60, 30);

        jLabel9.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel9.setText("Chicken piccata");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 290, 190, 40);

        jLabel10.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel10.setText("100");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 290, 50, 40);

        jLabel11.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel11.setText("Shish Tawook");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 340, 180, 50);

        jLabel12.setFont(new java.awt.Font("Aldhabi", 0, 36)); // NOI18N
        jLabel12.setText("80");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(230, 340, 50, 40);

        jLabel13.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel13.setText("Meat Fajita");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 400, 180, 40);

        jLabel15.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel15.setText("Grilled Mix Seafood");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 460, 210, 30);

        jLabel16.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel16.setText("90");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(230, 450, 40, 30);

        jLabel17.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel17.setText("Chicken fajita");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 510, 190, 50);

        jLabel18.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel18.setText("100");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(230, 510, 70, 30);

        jLabel19.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel19.setText("Chicken Buffalo");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 580, 190, 30);

        jLabel20.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel20.setText("35");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(230, 570, 40, 30);

        jLabel21.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel21.setText("Chicken Strips ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 620, 190, 50);

        jLabel22.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel22.setText("55");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(230, 630, 70, 30);

        jLabel23.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel23.setText("100");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(230, 400, 60, 30);

        jLabel14.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel14.setText("Name");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(350, 200, 80, 30);

        jLabel24.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel24.setText("Price");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(530, 200, 90, 30);

        jLabel25.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel25.setText("Cheese Cake");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(330, 250, 140, 50);

        jLabel26.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel26.setText("Ice Cream");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(330, 290, 110, 50);

        jLabel27.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel27.setText("55");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(550, 260, 50, 30);

        jLabel28.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel28.setText("25");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(550, 300, 50, 30);

        jLabel29.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel29.setText("Chocklet Cake");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(330, 340, 160, 50);

        jLabel30.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel30.setText("55");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(550, 350, 50, 30);

        jLabel31.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel31.setText("Brownies");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(330, 390, 110, 50);

        jLabel32.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel32.setText("55");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(550, 400, 50, 30);

        jLabel33.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel33.setText("Waffle");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(330, 450, 100, 50);

        jLabel34.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel34.setText("25");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(550, 460, 50, 30);

        jLabel35.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel35.setText("Fruite Salad");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(330, 500, 140, 50);

        jLabel36.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel36.setText("55");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(550, 500, 50, 30);

        jLabel37.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel37.setText("Molten Cake");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(330, 560, 140, 40);

        jLabel38.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel38.setText("55");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(550, 550, 30, 30);

        jLabel39.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel39.setText("Name");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(650, 200, 100, 30);

        jLabel40.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel40.setText("Price");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(820, 200, 80, 30);

        jLabel41.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel41.setText("Water");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(660, 250, 65, 30);

        jLabel42.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel42.setText("25");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(860, 250, 48, 30);

        jLabel43.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel43.setText("Turkish Coffee");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(660, 290, 160, 30);

        jLabel44.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel44.setText("55");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(860, 290, 48, 30);

        jLabel45.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel45.setText("Espresso");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(660, 330, 110, 30);

        jLabel46.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel46.setText("55");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(860, 330, 48, 30);

        jLabel47.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel47.setText("Macchiato");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(660, 370, 120, 30);

        jLabel48.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel48.setText("60");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(860, 370, 48, 30);

        jLabel49.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel49.setText("Strawberry Juice");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(660, 410, 180, 30);

        jLabel50.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel50.setText("35");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(860, 410, 48, 30);

        jLabel51.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel51.setText("Lemon Juice");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(660, 450, 140, 30);

        jLabel52.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel52.setText("35");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(860, 450, 48, 30);

        jLabel53.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel53.setText("Pineapple Juice");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(660, 490, 162, 30);

        jLabel54.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel54.setText("40");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(860, 490, 48, 30);

        jLabel55.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel55.setText("Lemon Mint Juice");
        getContentPane().add(jLabel55);
        jLabel55.setBounds(660, 540, 190, 30);

        jLabel56.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel56.setText("35");
        getContentPane().add(jLabel56);
        jLabel56.setBounds(860, 540, 48, 30);

        jLabel57.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel57.setText("Pepsi");
        getContentPane().add(jLabel57);
        jLabel57.setBounds(670, 580, 56, 30);

        jLabel58.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel58.setText("30");
        getContentPane().add(jLabel58);
        jLabel58.setBounds(860, 580, 48, 30);

        jLabel59.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel59.setText("Nescafe");
        getContentPane().add(jLabel59);
        jLabel59.setBounds(670, 620, 82, 30);

        jLabel60.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel60.setText("30");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(860, 620, 48, 30);

        jLabel61.setIcon(new javax.swing.ImageIcon("menuBackground.jpg")); // NOI18N
        getContentPane().add(jLabel61);
        jLabel61.setBounds(0, 0, 950, 700);
        

        pack();
             
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meals().setVisible(true);
                
        /* new Meals().setPreferredSize(new Dimension(900, 1000));
         new Meals().setLocationRelativeTo(null);
         new Meals().pack();*/
               
 /*           }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
   // private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
